title: SEER Data Hackathon
description: Two-day sprint to explore SEER data, collaborate across disciplines, and draft abstracts.
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
